spring:
  datasource:
    url: jdbc:sqlserver://cloud-assignment.database.windows.net:1433;database=Cloud_Assignment_DB;user=ankushmetla00@cloud-assignment;password={your_password_here};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: ankushmetla00
    password: password@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191